/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package pl.edu.agh.sr.rpc.laboratory.roboticarm;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ArmMovementType implements org.apache.thrift.TEnum {
  RAISE(1),
  DROP(2),
  ROTATE_RIGHT(3),
  ROTATE_LEFT(4);

  private final int value;

  private ArmMovementType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ArmMovementType findByValue(int value) { 
    switch (value) {
      case 1:
        return RAISE;
      case 2:
        return DROP;
      case 3:
        return ROTATE_RIGHT;
      case 4:
        return ROTATE_LEFT;
      default:
        return null;
    }
  }
}
