/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package pl.edu.agh.sr.rpc.laboratory.roboticarm;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-05-07")
public class PreciseRoboticArm {

  public interface Iface extends RoboticArm.Iface {

    public java.lang.String movePrecisely(ArmMovementType armMovementType, int angle) throws pl.edu.agh.sr.rpc.laboratory.InvalidOperationException, org.apache.thrift.TException;

  }

  public interface AsyncIface extends RoboticArm .AsyncIface {

    public void movePrecisely(ArmMovementType armMovementType, int angle, org.apache.thrift.async.AsyncMethodCallback<java.lang.String> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends RoboticArm.Client implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public java.lang.String movePrecisely(ArmMovementType armMovementType, int angle) throws pl.edu.agh.sr.rpc.laboratory.InvalidOperationException, org.apache.thrift.TException
    {
      send_movePrecisely(armMovementType, angle);
      return recv_movePrecisely();
    }

    public void send_movePrecisely(ArmMovementType armMovementType, int angle) throws org.apache.thrift.TException
    {
      movePrecisely_args args = new movePrecisely_args();
      args.setArmMovementType(armMovementType);
      args.setAngle(angle);
      sendBase("movePrecisely", args);
    }

    public java.lang.String recv_movePrecisely() throws pl.edu.agh.sr.rpc.laboratory.InvalidOperationException, org.apache.thrift.TException
    {
      movePrecisely_result result = new movePrecisely_result();
      receiveBase(result, "movePrecisely");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.e != null) {
        throw result.e;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "movePrecisely failed: unknown result");
    }

  }
  public static class AsyncClient extends RoboticArm.AsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void movePrecisely(ArmMovementType armMovementType, int angle, org.apache.thrift.async.AsyncMethodCallback<java.lang.String> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      movePrecisely_call method_call = new movePrecisely_call(armMovementType, angle, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class movePrecisely_call extends org.apache.thrift.async.TAsyncMethodCall<java.lang.String> {
      private ArmMovementType armMovementType;
      private int angle;
      public movePrecisely_call(ArmMovementType armMovementType, int angle, org.apache.thrift.async.AsyncMethodCallback<java.lang.String> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.armMovementType = armMovementType;
        this.angle = angle;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("movePrecisely", org.apache.thrift.protocol.TMessageType.CALL, 0));
        movePrecisely_args args = new movePrecisely_args();
        args.setArmMovementType(armMovementType);
        args.setAngle(angle);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public java.lang.String getResult() throws pl.edu.agh.sr.rpc.laboratory.InvalidOperationException, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_movePrecisely();
      }
    }

  }

  public static class Processor<I extends Iface> extends RoboticArm.Processor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("movePrecisely", new movePrecisely());
      return processMap;
    }

    public static class movePrecisely<I extends Iface> extends org.apache.thrift.ProcessFunction<I, movePrecisely_args> {
      public movePrecisely() {
        super("movePrecisely");
      }

      public movePrecisely_args getEmptyArgsInstance() {
        return new movePrecisely_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public movePrecisely_result getResult(I iface, movePrecisely_args args) throws org.apache.thrift.TException {
        movePrecisely_result result = new movePrecisely_result();
        try {
          result.success = iface.movePrecisely(args.armMovementType, args.angle);
        } catch (pl.edu.agh.sr.rpc.laboratory.InvalidOperationException e) {
          result.e = e;
        }
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends RoboticArm.AsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("movePrecisely", new movePrecisely());
      return processMap;
    }

    public static class movePrecisely<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, movePrecisely_args, java.lang.String> {
      public movePrecisely() {
        super("movePrecisely");
      }

      public movePrecisely_args getEmptyArgsInstance() {
        return new movePrecisely_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<java.lang.String> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<java.lang.String>() { 
          public void onComplete(java.lang.String o) {
            movePrecisely_result result = new movePrecisely_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            movePrecisely_result result = new movePrecisely_result();
            if (e instanceof pl.edu.agh.sr.rpc.laboratory.InvalidOperationException) {
              result.e = (pl.edu.agh.sr.rpc.laboratory.InvalidOperationException) e;
              result.setEIsSet(true);
              msg = result;
            } else if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, movePrecisely_args args, org.apache.thrift.async.AsyncMethodCallback<java.lang.String> resultHandler) throws org.apache.thrift.TException {
        iface.movePrecisely(args.armMovementType, args.angle,resultHandler);
      }
    }

  }

  public static class movePrecisely_args implements org.apache.thrift.TBase<movePrecisely_args, movePrecisely_args._Fields>, java.io.Serializable, Cloneable, Comparable<movePrecisely_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("movePrecisely_args");

    private static final org.apache.thrift.protocol.TField ARM_MOVEMENT_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("armMovementType", org.apache.thrift.protocol.TType.I32, (short)1);
    private static final org.apache.thrift.protocol.TField ANGLE_FIELD_DESC = new org.apache.thrift.protocol.TField("angle", org.apache.thrift.protocol.TType.I32, (short)2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new movePrecisely_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new movePrecisely_argsTupleSchemeFactory();

    /**
     * 
     * @see ArmMovementType
     */
    public ArmMovementType armMovementType; // required
    public int angle; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      /**
       * 
       * @see ArmMovementType
       */
      ARM_MOVEMENT_TYPE((short)1, "armMovementType"),
      ANGLE((short)2, "angle");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // ARM_MOVEMENT_TYPE
            return ARM_MOVEMENT_TYPE;
          case 2: // ANGLE
            return ANGLE;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __ANGLE_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.ARM_MOVEMENT_TYPE, new org.apache.thrift.meta_data.FieldMetaData("armMovementType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ArmMovementType.class)));
      tmpMap.put(_Fields.ANGLE, new org.apache.thrift.meta_data.FieldMetaData("angle", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(movePrecisely_args.class, metaDataMap);
    }

    public movePrecisely_args() {
    }

    public movePrecisely_args(
      ArmMovementType armMovementType,
      int angle)
    {
      this();
      this.armMovementType = armMovementType;
      this.angle = angle;
      setAngleIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public movePrecisely_args(movePrecisely_args other) {
      __isset_bitfield = other.__isset_bitfield;
      if (other.isSetArmMovementType()) {
        this.armMovementType = other.armMovementType;
      }
      this.angle = other.angle;
    }

    public movePrecisely_args deepCopy() {
      return new movePrecisely_args(this);
    }

    @Override
    public void clear() {
      this.armMovementType = null;
      setAngleIsSet(false);
      this.angle = 0;
    }

    /**
     * 
     * @see ArmMovementType
     */
    public ArmMovementType getArmMovementType() {
      return this.armMovementType;
    }

    /**
     * 
     * @see ArmMovementType
     */
    public movePrecisely_args setArmMovementType(ArmMovementType armMovementType) {
      this.armMovementType = armMovementType;
      return this;
    }

    public void unsetArmMovementType() {
      this.armMovementType = null;
    }

    /** Returns true if field armMovementType is set (has been assigned a value) and false otherwise */
    public boolean isSetArmMovementType() {
      return this.armMovementType != null;
    }

    public void setArmMovementTypeIsSet(boolean value) {
      if (!value) {
        this.armMovementType = null;
      }
    }

    public int getAngle() {
      return this.angle;
    }

    public movePrecisely_args setAngle(int angle) {
      this.angle = angle;
      setAngleIsSet(true);
      return this;
    }

    public void unsetAngle() {
      __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ANGLE_ISSET_ID);
    }

    /** Returns true if field angle is set (has been assigned a value) and false otherwise */
    public boolean isSetAngle() {
      return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ANGLE_ISSET_ID);
    }

    public void setAngleIsSet(boolean value) {
      __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ANGLE_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
      switch (field) {
      case ARM_MOVEMENT_TYPE:
        if (value == null) {
          unsetArmMovementType();
        } else {
          setArmMovementType((ArmMovementType)value);
        }
        break;

      case ANGLE:
        if (value == null) {
          unsetAngle();
        } else {
          setAngle((java.lang.Integer)value);
        }
        break;

      }
    }

    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case ARM_MOVEMENT_TYPE:
        return getArmMovementType();

      case ANGLE:
        return getAngle();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case ARM_MOVEMENT_TYPE:
        return isSetArmMovementType();
      case ANGLE:
        return isSetAngle();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof movePrecisely_args)
        return this.equals((movePrecisely_args)that);
      return false;
    }

    public boolean equals(movePrecisely_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_armMovementType = true && this.isSetArmMovementType();
      boolean that_present_armMovementType = true && that.isSetArmMovementType();
      if (this_present_armMovementType || that_present_armMovementType) {
        if (!(this_present_armMovementType && that_present_armMovementType))
          return false;
        if (!this.armMovementType.equals(that.armMovementType))
          return false;
      }

      boolean this_present_angle = true;
      boolean that_present_angle = true;
      if (this_present_angle || that_present_angle) {
        if (!(this_present_angle && that_present_angle))
          return false;
        if (this.angle != that.angle)
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetArmMovementType()) ? 131071 : 524287);
      if (isSetArmMovementType())
        hashCode = hashCode * 8191 + armMovementType.getValue();

      hashCode = hashCode * 8191 + angle;

      return hashCode;
    }

    @Override
    public int compareTo(movePrecisely_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetArmMovementType()).compareTo(other.isSetArmMovementType());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetArmMovementType()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.armMovementType, other.armMovementType);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetAngle()).compareTo(other.isSetAngle());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAngle()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.angle, other.angle);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("movePrecisely_args(");
      boolean first = true;

      sb.append("armMovementType:");
      if (this.armMovementType == null) {
        sb.append("null");
      } else {
        sb.append(this.armMovementType);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("angle:");
      sb.append(this.angle);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class movePrecisely_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public movePrecisely_argsStandardScheme getScheme() {
        return new movePrecisely_argsStandardScheme();
      }
    }

    private static class movePrecisely_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<movePrecisely_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, movePrecisely_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // ARM_MOVEMENT_TYPE
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.armMovementType = pl.edu.agh.sr.rpc.laboratory.roboticarm.ArmMovementType.findByValue(iprot.readI32());
                struct.setArmMovementTypeIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // ANGLE
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.angle = iprot.readI32();
                struct.setAngleIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, movePrecisely_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.armMovementType != null) {
          oprot.writeFieldBegin(ARM_MOVEMENT_TYPE_FIELD_DESC);
          oprot.writeI32(struct.armMovementType.getValue());
          oprot.writeFieldEnd();
        }
        oprot.writeFieldBegin(ANGLE_FIELD_DESC);
        oprot.writeI32(struct.angle);
        oprot.writeFieldEnd();
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class movePrecisely_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public movePrecisely_argsTupleScheme getScheme() {
        return new movePrecisely_argsTupleScheme();
      }
    }

    private static class movePrecisely_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<movePrecisely_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, movePrecisely_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetArmMovementType()) {
          optionals.set(0);
        }
        if (struct.isSetAngle()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetArmMovementType()) {
          oprot.writeI32(struct.armMovementType.getValue());
        }
        if (struct.isSetAngle()) {
          oprot.writeI32(struct.angle);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, movePrecisely_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.armMovementType = pl.edu.agh.sr.rpc.laboratory.roboticarm.ArmMovementType.findByValue(iprot.readI32());
          struct.setArmMovementTypeIsSet(true);
        }
        if (incoming.get(1)) {
          struct.angle = iprot.readI32();
          struct.setAngleIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class movePrecisely_result implements org.apache.thrift.TBase<movePrecisely_result, movePrecisely_result._Fields>, java.io.Serializable, Cloneable, Comparable<movePrecisely_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("movePrecisely_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);
    private static final org.apache.thrift.protocol.TField E_FIELD_DESC = new org.apache.thrift.protocol.TField("e", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new movePrecisely_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new movePrecisely_resultTupleSchemeFactory();

    public java.lang.String success; // required
    public pl.edu.agh.sr.rpc.laboratory.InvalidOperationException e; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      E((short)1, "e");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // E
            return E;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.E, new org.apache.thrift.meta_data.FieldMetaData("e", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, pl.edu.agh.sr.rpc.laboratory.InvalidOperationException.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(movePrecisely_result.class, metaDataMap);
    }

    public movePrecisely_result() {
    }

    public movePrecisely_result(
      java.lang.String success,
      pl.edu.agh.sr.rpc.laboratory.InvalidOperationException e)
    {
      this();
      this.success = success;
      this.e = e;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public movePrecisely_result(movePrecisely_result other) {
      if (other.isSetSuccess()) {
        this.success = other.success;
      }
      if (other.isSetE()) {
        this.e = new pl.edu.agh.sr.rpc.laboratory.InvalidOperationException(other.e);
      }
    }

    public movePrecisely_result deepCopy() {
      return new movePrecisely_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
      this.e = null;
    }

    public java.lang.String getSuccess() {
      return this.success;
    }

    public movePrecisely_result setSuccess(java.lang.String success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public pl.edu.agh.sr.rpc.laboratory.InvalidOperationException getE() {
      return this.e;
    }

    public movePrecisely_result setE(pl.edu.agh.sr.rpc.laboratory.InvalidOperationException e) {
      this.e = e;
      return this;
    }

    public void unsetE() {
      this.e = null;
    }

    /** Returns true if field e is set (has been assigned a value) and false otherwise */
    public boolean isSetE() {
      return this.e != null;
    }

    public void setEIsSet(boolean value) {
      if (!value) {
        this.e = null;
      }
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((java.lang.String)value);
        }
        break;

      case E:
        if (value == null) {
          unsetE();
        } else {
          setE((pl.edu.agh.sr.rpc.laboratory.InvalidOperationException)value);
        }
        break;

      }
    }

    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      case E:
        return getE();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case E:
        return isSetE();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof movePrecisely_result)
        return this.equals((movePrecisely_result)that);
      return false;
    }

    public boolean equals(movePrecisely_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      boolean this_present_e = true && this.isSetE();
      boolean that_present_e = true && that.isSetE();
      if (this_present_e || that_present_e) {
        if (!(this_present_e && that_present_e))
          return false;
        if (!this.e.equals(that.e))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      hashCode = hashCode * 8191 + ((isSetE()) ? 131071 : 524287);
      if (isSetE())
        hashCode = hashCode * 8191 + e.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(movePrecisely_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetE()).compareTo(other.isSetE());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetE()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.e, other.e);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("movePrecisely_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("e:");
      if (this.e == null) {
        sb.append("null");
      } else {
        sb.append(this.e);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class movePrecisely_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public movePrecisely_resultStandardScheme getScheme() {
        return new movePrecisely_resultStandardScheme();
      }
    }

    private static class movePrecisely_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<movePrecisely_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, movePrecisely_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.success = iprot.readString();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // E
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.e = new pl.edu.agh.sr.rpc.laboratory.InvalidOperationException();
                struct.e.read(iprot);
                struct.setEIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, movePrecisely_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeString(struct.success);
          oprot.writeFieldEnd();
        }
        if (struct.e != null) {
          oprot.writeFieldBegin(E_FIELD_DESC);
          struct.e.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class movePrecisely_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public movePrecisely_resultTupleScheme getScheme() {
        return new movePrecisely_resultTupleScheme();
      }
    }

    private static class movePrecisely_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<movePrecisely_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, movePrecisely_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetE()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetSuccess()) {
          oprot.writeString(struct.success);
        }
        if (struct.isSetE()) {
          struct.e.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, movePrecisely_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.success = iprot.readString();
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.e = new pl.edu.agh.sr.rpc.laboratory.InvalidOperationException();
          struct.e.read(iprot);
          struct.setEIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
