#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
import sys
import laboratory.ttypes

from thrift.transport import TTransport


class ArmMovementType(object):
    RAISE = 1
    DROP = 2
    ROTATE_RIGHT = 3
    ROTATE_LEFT = 4

    _VALUES_TO_NAMES = {
        1: "RAISE",
        2: "DROP",
        3: "ROTATE_RIGHT",
        4: "ROTATE_LEFT",
    }

    _NAMES_TO_VALUES = {
        "RAISE": 1,
        "DROP": 2,
        "ROTATE_RIGHT": 3,
        "ROTATE_LEFT": 4,
    }
